### ISSUE TITLE
[v1.1.4~] soでないチャンネル動画で貢献度ランキングが表示されない

### ISSUE THREAD

**Issue by AyumuNekozuki** [AyumuNekozuki/nicoad-ex#1]
URLがsoでないチャンネル動画（/watch/XXXX）で、貢献度ランキングが正常に表示されない

左：ポップアップでの正常表示
右：拡張機能でのコメント欄表示
![image](https://user-images.githubusercontent.com/47974873/81632700-e989d500-9445-11ea-84f8-39d15e299764.png)

## 環境
- Google Chrome 81.0
- ニコニ広告ex. v1.1.4

## 条件
URLの動画IDがso表示でないチャンネル動画
例：/watch/1588209123

## 原因
通常、動画IDがsoに置き換えられて広告画面が表示されるが、置き換えずに表示させているため貢献度ランキングが共通化されないのでは

## 対応
/watch/XXXXX を /watch/soXXXX へ置き換えて動画IDを取得する必要がある。
現在仕様検討中

**Comment by AyumuNekozuki** [comment]
メモ：https://ext.nicovideo.jp/api/getthumbinfo/ + nicoID で動画情報をXML形式で取得可能。

```
例：watch/1590456066
https://ext.nicovideo.jp/api/getthumbinfo/1590456066
→ video_id: so36925642
→ genre: アニメ
→ ch_id: 2632720
→ ch_name: dアニメストア ニコニコ支店
などいろいろ
```

なお、www.nicovideo.jp から叩くと CORS に阻まれる

**Comment by AyumuNekozuki** [comment]
v1.2.0でのバグ修復を延期しました。

**Comment by tearaikazuki** [comment]
動画ページ内でso形式のID取れそうだからそれ取ってあげればどうにかなりそう
