### ISSUE TITLE
[v2.0.0] Windows環境下でRounded M+フォントがガビガビになる

### ISSUE THREAD

**Issue by AyumuNekozuki** [AyumuNekozuki/nicoad-ex#25]
## 現在
- Windows環境下でRounded M+フォントがガビガビで表示されてしまい見ずらい
![image](https://user-images.githubusercontent.com/47974873/121374630-02332a00-c97b-11eb-8061-ddf8524fc81b.png)

### 備考
- Macでは発生しない

## 改善策
0.03° 傾けると良いらしい？
https://irokoto.co.jp/blog/20200911/post-16

**Comment by yukiyalien** [comment]
close後に失礼。
どうやらTrueTypeかなんかのヒンティング情報が悪さしているらしい感じがあるので、ヒンティング情報を爆破して排除済になったフォントを使うと傾けなくてもいい感じになるかもしれません。
現在Google Fontsを使っているようなので、移行するとしたらかなり大変ですが…。ぶっちゃけ今の状態で大丈夫そうならそのままでいいかもしれませんね。

https://qiita.com/AumyF/items/af5faa689c6700e4ea3a
https://qiita.com/AumyF/items/7d268134f5915f222599
https://qiita.com/AumyF/items/4f625ebd47603efaac7a

**Comment by AyumuNekozuki** [comment]
なるほどなぁ
まぁ拡張機能のメニューの文字だけだし、移行が~~面倒~~大変なのでとりあえず現状のまま行こうと思います！
ありがとうございますー！
