### ISSUE TITLE
[v2.0.2] パネルヘッダの▲要素の位置がズレている

### ISSUE THREAD

**Issue by AyumuNekozuki** [AyumuNekozuki/nicoad-ex#31]
## 内容 
マイリストとニコニ広告ex.のパネルヘッダにおいて、div.AddVideoListPanelContainer::before要素のstyleのleftの数値が、おそらく間違っています。

該当する行
https://github.com/AyumuNekozuki/nicoad-ex/blob/master/js/script.js#L58
https://github.com/AyumuNekozuki/nicoad-ex/blob/master/js/script.js#L63

各要素の幅から計算すると広告のleftは188px、マイリストのleftは152px（ニコ動のデフォルトでは153pxだが多分これも間違い）が正しいと思われます。
 
## 問題が発生したURL 
すべての動画再生ページ
 
## 環境 
Chrome
 
## From 
おこうfrom GForm

**Comment by Thiroaki** [comment]
Issue投げた人です。
forkして修正したので、後ほどPR出しておきます。
