### ISSUE TITLE
[v2.1.0] 広告ドロワーの出し入れがブラウザのヒストリに残る

### ISSUE THREAD

**Issue by Thiroaki** [AyumuNekozuki/nicoad-ex#35]
## 内容
静画、大百科、立体で追加された右側の広告ドロワーを出し入れすると、同じページの履歴（正確にはiframeの変更履歴）がブラウザのヒストリ（戻る進む）に溜まっていく。
iframeのsrcを直接書き換えるとブラウザのヒストリに残るらしい。

## 改善策
`contentWindow.location.replace()`を使うと残らない。
https://www.takurokamiyoshi.net/blog/57/

**Comment by AyumuNekozuki** [comment]
あれ履歴に残るのか...
修正しますー🙏

**Comment by AyumuNekozuki** [comment]
修正完了しました！ありがとうございます！
